### ISSUE TITLE
Removing Openshift* pods after minikube install

### ISSUE THREAD

**Issue by kameshsampath** [openshift-cloud-functions/knative-operators#24]
It will be nice to remove all openshfit* pods from the minikube after install. This does not have any problem but just to keep install clean

```
openshift-operator-lifecycle-manager   catalog-operator-756b9b7d64-fs5mt               0/1     CrashLoopBackOff   6          32h
openshift-operator-lifecycle-manager   knative-operators-mvf7d                         0/1     CrashLoopBackOff   6          32h
openshift-operator-lifecycle-manager   maistra-operators-h84zs                         0/1     CrashLoopBackOff   6          32h
openshift-operator-lifecycle-manager   olm-operator-59b445c7fc-wt4tj                   0/1     CrashLoopBackOff   7          32h
openshift-operator-lifecycle-manager   olm-operators-hh9gr                             0/1     CrashLoopBackOff   6          32h
k
```

**Comment by jcrossley3** [comment]
I would rather not do this, since we're using OLM in the script to install knative via subscriptions to the operators, which are of course managed by OLM. So deleting these is a little weird. An alternative is to change the script (or add an option) to not install OLM at all, and simply install the upstream yaml manifests according to their upstream docs. I'm not convinced of the value of doing that, tbh.
